// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE0w0b6mr75YZ4QZug2OAkf1rr6J1DKz0',
    appId: '1:976879132945:web:6299700e1bd80aa4ba6cb0',
    messagingSenderId: '976879132945',
    projectId: 'aksingh-33aff',
    authDomain: 'aksingh-33aff.firebaseapp.com',
    storageBucket: 'aksingh-33aff.appspot.com',
    measurementId: 'G-5ZRGYX3J6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcFWQVNnfDe8qofnMXWZq9z5X66kwQHoU',
    appId: '1:976879132945:android:cf5e3e055451f559ba6cb0',
    messagingSenderId: '976879132945',
    projectId: 'aksingh-33aff',
    storageBucket: 'aksingh-33aff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQySC2oIoZ8Qdv52ZbmtpaC4SCAfbS4As',
    appId: '1:976879132945:ios:6d41f9b00c23f33eba6cb0',
    messagingSenderId: '976879132945',
    projectId: 'aksingh-33aff',
    storageBucket: 'aksingh-33aff.appspot.com',
    iosBundleId: 'com.example.mvvmgetx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQySC2oIoZ8Qdv52ZbmtpaC4SCAfbS4As',
    appId: '1:976879132945:ios:6d41f9b00c23f33eba6cb0',
    messagingSenderId: '976879132945',
    projectId: 'aksingh-33aff',
    storageBucket: 'aksingh-33aff.appspot.com',
    iosBundleId: 'com.example.mvvmgetx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE0w0b6mr75YZ4QZug2OAkf1rr6J1DKz0',
    appId: '1:976879132945:web:fe4aa5fbfa1669cfba6cb0',
    messagingSenderId: '976879132945',
    projectId: 'aksingh-33aff',
    authDomain: 'aksingh-33aff.firebaseapp.com',
    storageBucket: 'aksingh-33aff.appspot.com',
    measurementId: 'G-EFPNVDD6B2',
  );
}
